# Generated by Django 6.0.6 on 2026-06-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF'), ('DOCX', 'DOCX')], max_length=4),
        ),
        migrations.AlterField(
            model_name='document',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
