# Generated by Django 6.0.6 on 2026-06-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_document_file_type_alter_document_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='raw_input',
            field=models.TextField(),
        ),
    ]
