# Generated by Django 6.0.6 on 2026-07-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incident_raw_input'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-created_at']},
        ),
    ]
