# Generated by Django 6.0.6 on 2026-07-05 12:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_alter_document_options_alter_document_file_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='suggested_fixes',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='incident',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='affected_systems',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='prevention',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='root_cause',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('CRITICAL', 'Critical'), ('HIGH', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='timeline',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
