# Generated by Django 6.0.6 on 2026-07-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_rename_suggested_fixes_incident_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='resolution',
            field=models.TextField(),
        ),
    ]
